name: 'build'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
        qt-version: ['5.13.2', '5.15.0']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # https://github.com/marketplace/actions/install-qt
    - if: contains( matrix.os, 'windows')
      name: Install Qt on Windows
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
        arch: win64_mingw53
    - if: ! contains( matrix.os, 'windows')
      name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt-version }}
    - name: qmake & make
      run: |
        qmake qcompilerexplorer.pro
        make
